### ISSUE TITLE
Internal Server Error when viewing character details on the team roster

### ISSUE THREAD

**Issue by Bonkeybee** [Elite747/ValhallaLootList#64] opened 2021-04-18 01:04 UTC
![image](https://user-images.githubusercontent.com/9619823/115130801-25171280-9fb8-11eb-9005-fb54e50dbd6d.png)

**Comment by Elite747** [comment] 2021-04-27 03:08
This was caused by sending too many requests to Discord's API. This should be fixed now with using the Gateway which will preload the entire guild roster, removing the need to make an API request per character.

**Closed by Elite747** 2021-04-27 03:08 UTC
Labels: P1
